"""bodies table

Revision ID: 341f1c21dd18
Revises: 
Create Date: 2019-01-15 22:18:18.571215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341f1c21dd18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('horizon_id', sa.Integer(), nullable=True),
    sa.Column('wiki', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_name'), 'body', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_body_name'), table_name='body')
    op.drop_table('body')
    # ### end Alembic commands ###
