"""deltas

Revision ID: 4eead2cd50ab
Revises: 341f1c21dd18
Create Date: 2019-01-15 22:42:37.420204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eead2cd50ab'
down_revision = '341f1c21dd18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('au', sa.Float(), nullable=True),
    sa.Column('body_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['body_id'], ['body.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delta_time'), 'delta', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delta_time'), table_name='delta')
    op.drop_table('delta')
    # ### end Alembic commands ###
